language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
python:
  - 2.7
env:
  matrix:
    - PLONE_VERSION=4.3
    - PLONE_VERSION=5.0
matrix:
  fast_finish: true
install:
  - sed -ie "s#5.0-latest#$PLONE_VERSION-latest#" buildout.cfg
  - virtualenv .
  - bin/pip install --upgrade -r requirements.txt
  - bin/buildout -n buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -n buildout:download-cache=downloads code-analysis:return-status-codes=True
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - m.van.rees@zestsoftware.nl
